name: 保持活躍狀態
on:
    push:
    schedule:
        - cron: '0 8 */7 * *'
jobs:
    avoid:
        name: 保持 Github Action 活躍狀態
        runs-on: ubuntu-latest
        steps:
        - name: 檢查
          uses: actions/checkout@master
        - name: 建立 commits
          run: |
              echo "avoid" >> avoid.txt
              git config --global user.name "Github Action"
              git config --global user.email "action@github.com"
              git add .
              git commit -m "Avoiding workflow being suspended."
              git push